language: python
sudo: false
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=flake8
install:
  - travis_retry pip install tox
script:
  - tox

after_script:
  - |
      env | sort
      if [ ! -f coverage.xml ]; then
          echo "No coverage.xml found; skipping sending coverage to couverture.io"
          return
      fi
      if [ $TRAVIS_PULL_REQUEST != false ]; then
          REAL_COMMIT=$(git log -n 1 $TRAVIS_COMMIT_RANGE --format="%H")
          PR_NUM=$TRAVIS_PULL_REQUEST
      else
          REAL_COMMIT=$TRAVIS_COMMIT
      fi
      curl \
          --verbose --insecure \
          --header "X-Couverture-Pull-Request: $PR_NUM" \
          --data-binary @coverage.xml \
          "https://app.couverture.io/coverage/github/SurveyMonkey/pyteamcity/$REAL_COMMIT/$TOXENV"
